### PR TITLE
Updated for Express 4.

### PR DESCRIPTION
**Pull request by RyanBreaker**
Thank you much for the guide, it helped me understand how to use passport correctly. I had to do some work on my own to get it to work with Express 4 but was an easy update. Forked and updated such that just the template is updated for Express 4, should also make updating the guide easy as well.

### CODE REVIEW

**Comment by mjhea0** [comment]
The only problem with this is that now I will have to update the blog post. 

I could -
1. update the current blog post
2. create a new blog post
3. do not update the blog post, and just add this code as a new branch

What are your thoughts?

**Comment by mjhea0** [comment]
Thanks so much for doing this btw! :+1:

**Comment by mjhea0** [comment]
Working on a new blog post -> https://gist.github.com/mjhea0/93266da1113249d9fea2

**Comment by RyanBreaker** [comment]
Awesome, that's what I would think of recommending, actually.

Just a note, I was unable to port forward the testing suite, so don't rely on the code for that part to be up-to-date as well.

**Comment by mjhea0** [comment]
http://mherman.org/blog/2015/01/31/local-authentication-with-passport-and-express-4/#.VM13YFXF8Yc

**Pull request closed without merging**
